Melina
akuzminykh/MaterialScannerHsH pull request #4
Opened 2021-04-16 13:43 UTC by Melina-Wi

Chages by Kristin and Melina:
- Cached the rotationmatrix. The calculation is outsourced in functions.
- Matrix-multiplication outsourced from the thread.
- fit the calculation of orientationFactor in x-rotation-matrix.

2021-04-16 18:23 UTC, akuzminykh requested changes
Wenn es keinen Stress macht, dann die Commits vor dem Merge alle squashen.

2021-04-16 18:23 UTC, akuzminykh commented on src/main.cpp
> +	}
Das geht auch mit einem ternären Operator: `const size_t heightCalc = height % 2 != 0 ? height - 1 : height;`. Analog mit `width`.

2021-04-16 18:23 UTC, akuzminykh commented on src/main.cpp
> +Vec orientationCorrection(const Vec& v, const int x, const Mat& rotX, const vector<Mat>& rotY)
Das kann weg.

2021-04-16 18:23 UTC, akuzminykh commented on src/main.cpp
> +}
Bitte sauber formattieren; da sind Tabs zu viel.

2021-04-16 18:23 UTC, akuzminykh commented on src/main.cpp
> +Mat matRotX(const double factor, const int y, const size_t height, const size_t width) {
Die Funktion braucht `width` nicht. Das ist, was ich letzten Freitag erklärt hatte. Berechnet das Verhältnis einfach außerhalb der Funktion und ihr spart euch eine Menge Operationen.

2021-04-16 18:23 UTC, akuzminykh commented on src/main.cpp
> +		const double degY = (static_cast<double>(x) / (width - 1) * 2.0 - 1.0) * rotFacY;
Optional: Wenn ihr `vector<Mat>` zurückgebt, dann spart ihr euch das hier. Dann könnt ihr z. B. mit einer Schleife von Minimum zum Maximum für `degY` gehen und dabei die Matrizen erstellen. Analog für die andere Funktion.

2021-04-16 18:23 UTC, akuzminykh commented on src/main.cpp
> +	}
Wenn man einfach `width` und `height` vom ersten Bild nimmt, dann muss man mit der Schleife nurnoch die Werte der anderen Bilder vergleichen, man hat also kein `i+1` und eine Warnung wegen Overflow. So müsste die Schleife nicht mit einem `size_t` iterieren.

2021-04-16 18:23 UTC, akuzminykh commented on src/main.cpp
> +	}
Wenn die Bilder verschiedene Größen haben, dann ist das kein Programmierfehler, sondern ein Fehler bei der Eingabe, also des Benutzers. Deshalb das hier so umschreiben, dass eine Exception geworfen und eine Fehlermeldung ausgeben wird, statt `assert` zu benutzen.

2021-04-16 18:23 UTC, akuzminykh commented on src/main.cpp
> +			[y, width, height, nImages, correctionFactor, &dataset, &L_inverseTransposed, rotX, &rotY] {
`height` und `correctionFactor` werden vom Lambda benutzt, also weg. `rotX` als Referenz übergeben.

2021-04-16 18:23 UTC, akuzminykh commented on src/main.cpp
> +					//cout << normal[0] << "  " << normal[1] << "  " << normal[2] <<"\n";
Code sauber halten.

2021-04-19 06:24 UTC, Melina-Wi commented
> Wenn es keinen Stress macht, dann die Commits vor dem Merge alle squashen.

Das habe ich noch nie gemacht. Könnten wir das mal zusammen machen? :)

2021-04-19 07:16 UTC, akuzminykh commented
> Das habe ich noch nie gemacht. Könnten wir das mal zusammen machen? :)

Klar, können wir ja direkt um 17 Uhr anschauen! (:

2021-04-19 14:48 UTC, KristinSiegmundHH commented on src/main.cpp
> +#include <time.h>
die zeitmessung kann aber eigentlich auch wieder komplett rausgenommmen werden oder? das war ja nur für uns um zu sehen ob es eine zeitliche verbesserung gab.

2021-04-19 14:55 UTC, KristinSiegmundHH commented on src/main.cpp
> +					//cout << normal[0] << "  " << normal[1] << "  " << normal[2] <<"\n";
✔️

2021-04-19 14:55 UTC, KristinSiegmundHH commented on src/io.hpp
> +Mat matRotY(const double factor, const int x, const size_t width);
✔️

2021-04-19 14:56 UTC, KristinSiegmundHH commented on src/io.hpp
> +Mat matRotY(const double factor, const int x, const size_t width);
✔️

2021-04-19 14:57 UTC, KristinSiegmundHH commented on src/main.cpp
> +		const double degY = (static_cast<double>(x) / (width - 1) * 2.0 - 1.0) * rotFacY;
?

2021-04-20 18:27 UTC, KristinSiegmundHH commented on src/io.hpp
> +Mat matRotY(const double factor, const int x, const size_t width);
✔️

2021-04-20 18:38 UTC, KristinSiegmundHH commented on src/main.cpp
> +#include <time.h>
✔️

2021-04-20 18:38 UTC, KristinSiegmundHH commented on src/main.cpp
> +	tstart = clock();
✔️

2021-04-20 18:38 UTC, KristinSiegmundHH commented on src/main.cpp
> +	cout << "  time = " << time1 << " sec.";
✔️

2021-04-20 18:38 UTC, KristinSiegmundHH commented on src/main.cpp
> +	tstart = clock();
✔️

2021-04-20 18:38 UTC, KristinSiegmundHH commented on src/main.cpp
> +	}
✔️

2021-04-20 18:41 UTC, KristinSiegmundHH commented on src/main.cpp
> +	}
✔️

2021-04-20 18:45 UTC, KristinSiegmundHH commented on src/main.cpp
> +Vec orientationCorrection(const Vec& v, const int x, const Mat& rotX, const vector<Mat>& rotY)
✔️

2021-04-20 18:46 UTC, KristinSiegmundHH commented on src/main.cpp
> +}
✔️

2021-04-20 18:46 UTC, KristinSiegmundHH commented on src/main.cpp
> +Mat matRotX(const double factor, const int y, const size_t height, const size_t width) {
✔️

2021-04-20 19:26 UTC, KristinSiegmundHH commented on src/main.cpp
> +	}
✔️

2021-04-20 19:26 UTC, KristinSiegmundHH commented on src/main.cpp
> +	}
✔️

2021-04-20 19:27 UTC, KristinSiegmundHH commented on src/main.cpp
> +			[y, width, height, nImages, correctionFactor, &dataset, &L_inverseTransposed, rotX, &rotY] {
rotX muss ein Value sein. 
✔️

2021-04-20 20:50 UTC, KristinSiegmundHH commented on src/main.cpp
> +		const double degY = (static_cast<double>(x) / (width - 1) * 2.0 - 1.0) * rotFacY;
wip

2021-04-20 21:04 UTC, KristinSiegmundHH commented on src/main.cpp
> +	double addFactorY = -1;
@akuzminykh das ist noch WIP. Kommentar ist noch irreführend und naming der Variablen noch nicht ganz passend

2021-04-21 08:24 UTC, akuzminykh requested changes
Die Sache mit dem Iterieren habe ich nicht angeguckt, wie gewünscht.

2021-04-21 08:24 UTC, akuzminykh commented on src/main.cpp
> +		const Mat rotX = correctiveRotationX(correctionFactor, y, height, sizeRatio, addFactorX);
`sizeRatio` einfach direkt auf `correctionFactor` multiplizieren und der extra Parameter kann weg.

2021-04-21 08:24 UTC, akuzminykh commented on src/io.cpp
> +	for (int i = 0; i < dataset.size(); ++i) {
Bei `i = 1` starten.

2021-05-02 18:29 UTC, akuzminykh requested changes
Fast am Ziel. :D

2021-05-02 18:29 UTC, akuzminykh commented on src/main.cpp
> +	cout << "Calculation Time Normalmap (sec) = " << (duration_cast<microseconds>(end - begin).count()) / 1000000.0 << std::endl;
Packt das vor `writeNormalMap`. Wie schnell das geschrieben wird, können wir auch nicht beeinflussen.

2021-05-02 18:29 UTC, akuzminykh commented on src/main.cpp
> +Mat correctiveRotationY(const double radians, const size_t width, const double addFactor) {
`width` wird gar nicht benutzt

2021-05-02 18:29 UTC, akuzminykh commented on src/main.cpp
> +Mat correctiveRotationX(const double radians, const size_t height, const double addFactor) {
`height` wird gar nicht benutzt.

2021-05-02 18:29 UTC, akuzminykh commented on src/main.cpp
> +	const double radX = addFactor * radians;
Ich finde es irgendwie strange einen Parameter, also `addFactor`, nur dafür zu haben, um den einmal auf einen anderen zu multiplizieren. Schmeißt den weg und macht das direkt bei der Übergabe.

2021-05-02 18:29 UTC, akuzminykh commented on src/main.cpp
> +	const double radY = addFactor * radians;
Ich finde es irgendwie strange einen Parameter, also `addFactor`, nur dafür zu haben, um den einmal auf einen anderen zu multiplizieren. Schmeißt den weg und macht das direkt bei der Übergabe.

2021-05-02 18:29 UTC, akuzminykh commented on src/main.cpp
> +Mat correctiveRotationX(const double radians, const size_t height, const double addFactor) {
Wenn `height` und `addFactor` weg sind, dann macht die Funktion nichts anderes als einfach nur eine Rotationsmatrix zu erstellen. Da ist kein Bezug mehr zu "corrective". Nennt die einfach `rotationX` und packt das in `Mat` als statische (`static`) Funktion.

2021-05-02 18:29 UTC, akuzminykh commented on src/main.cpp
> +Mat correctiveRotationY(const double radians, const size_t width, const double addFactor) {
Wenn `height` und `addFactor` weg sind, dann macht die Funktion nichts anderes als einfach nur eine Rotationsmatrix zu erstellen. Da ist kein Bezug mehr zu "corrective". Nennt die einfach `rotationY` und packt das in `Mat` als statische (`static`) Funktion.

2021-05-02 18:29 UTC, akuzminykh commented on src/main.cpp
> +			[y, width, nImages, &dataset, &L_inverseTransposed, rotX, &rotY] {
Das ist mir zu viel Kram in `main` jetzt. Lagert das in eigene Funktionen aus. Tipp: Indem ihr zwei Funktionen schreibt, die `vector<Mat>` zurückgeben, jeweils für Zeilen und Spalten, wo die ganzen Matrizen für die Korrektur drin sind.

2021-05-06 13:19 UTC, KristinSiegmundHH commented on src/main.cpp
> +	cout << "Calculation Time Normalmap (sec) = " << (duration_cast<microseconds>(end - begin).count()) / 1000000.0 << std::endl;
✔️

2021-05-06 13:24 UTC, KristinSiegmundHH commented on src/main.cpp
> +Mat correctiveRotationX(const double radians, const size_t height, const double addFactor) {
✔️

2021-05-06 13:24 UTC, KristinSiegmundHH commented on src/main.cpp
> +Mat correctiveRotationY(const double radians, const size_t width, const double addFactor) {
✔️

2021-05-06 13:35 UTC, KristinSiegmundHH commented on src/main.cpp
> +	const double radX = addFactor * radians;
✔️

2021-05-06 13:36 UTC, KristinSiegmundHH commented on src/main.cpp
> +	const double radY = addFactor * radians;
✔️

2021-05-06 13:44 UTC, KristinSiegmundHH commented on src/main.cpp
> +Mat correctiveRotationX(const double radians, const size_t height, const double addFactor) {
✔️

2021-05-06 13:45 UTC, KristinSiegmundHH commented on src/main.cpp
> +Mat correctiveRotationY(const double radians, const size_t width, const double addFactor) {
✔️

2021-05-06 15:25 UTC, KristinSiegmundHH commented on src/main.cpp
> +			[y, width, nImages, &dataset, &L_inverseTransposed, rotX, &rotY] {
✔️

2021-05-26 11:01 UTC, merged